import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import "../styling/Galaxy.css";
const Galaxy = () => {
    return (_jsxs("div", { className: "galaxy", children: [_jsx("img", { className: "fade-in gal-img", src: "/Home/galaxy2.jpeg" }), _jsxs("div", { className: "d-flex fade-in vh-100 align-items-center justify-content-center", children: [_jsxs("div", { className: "d-flex space-text flex-column title-cont", children: [_jsx("h1", { className: "space-title", children: "Hi! \u2B50\uFE0F I'm Ashley, it's nice to meet you!" }), _jsx("h3", { className: "space-mid", children: "I am currently a freshman in the Texas A&M Engineering Honors program pursuing a B.S. in Computer Science. My passions include software engineering, data analytics, and surprisingly fashion \uD83D\uDC60. I have experience in full-stack web development, machine learning, databases, scripting, and data visualization. Right now, I'm on the lookout for a 2024 summer SWE / data analytics internship so... feel free to message me or email me at ashlxyzhang@tamu.edu! \uD83D\uDE0A" }), _jsxs("h5", { className: "space-subtitle", children: ["This website is an extension of my mind as a galaxy.", _jsx("br", {}), "Feel free to explore it & enjoy!"] })] }), _jsxs("span", { className: "space-text", style: {
                            fontSize: 10,
                            textAlign: "center",
                            alignSelf: "end",
                            zIndex: 1,
                        }, children: ["Made with \uD83D\uDC9B by \uD83C\uDF4E ", _jsx("br", {}), "\u00A9 2024. All rights reserved."] }), _jsxs("div", { className: "d-flex vh-100 align-items-center justify-content-center", children: [_jsxs("div", { className: "dest-cont", style: { marginBottom: "2%", marginRight: "7%" }, children: [_jsx(Link, { to: "/", className: "destination", children: "\uD83C\uDF0E" }), _jsx("div", { className: "dest-cap", children: _jsx("span", { children: "Home (Earth)" }) })] }), _jsxs("div", { className: "dest-cont", style: { marginBottom: "11%", marginRight: "15%" }, children: [_jsx(Link, { to: "/advent", className: "destination", children: "\uD83D\uDCAB" }), _jsx("span", { className: "dest-cap", children: "Advent Calendar" })] }), _jsxs("div", { className: "dest-cont", style: { marginTop: "15%", marginLeft: "5%" }, children: [_jsx(Link, { to: "/phonebook", className: "destination", children: "\uD83E\uDE90" }), _jsx("span", { className: "dest-cap", children: "Phonebook" })] }), _jsxs("div", { className: "dest-cont", style: { marginBottom: "4%", marginRight: "20%" }, children: [_jsx(Link, { to: "/italy", className: "destination", children: "\uD83C\uDF0C" }), _jsx("span", { className: "dest-cap", children: "Italy Photos" })] })] })] })] }));
};
export default Galaxy;
