import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import ItalyGrid from "./components/Italy/ItalyGrid";
import GetItalyImages from "./components/Italy/ItalyImages";
import GetItalyCaps from "./components/Italy/ItalyCaps";
import Tracks from "./components/Phonebook/Tracks";
import Home from "./components/Home";
import Galaxy from "./components/Galaxy";
import Advent from "./components/Advent/Advent";
import One from "./components/Advent/One";
import Two from "./components/Advent/Two";
import Three from "./components/Advent/Three";
import Eight from "./components/Advent/Eight";
import Nine from "./components/Advent/Nine";
import Ten from "./components/Advent/Ten";
import Eleven from "./components/Advent/Eleven";
import Twelve from "./components/Advent/Twelve";
import Thirteen from "./components/Advent/Thirteen";
import Fourteen from "./components/Advent/Fourteen";
import Fifteen from "./components/Advent/Fifteen";
import Sixteen from "./components/Advent/Sixteen";
import Seventeen from "./components/Advent/Seventeen";
const App = () => {
    const italyImages = GetItalyImages();
    const italyCaps = GetItalyCaps();
    return (_jsx(_Fragment, { children: _jsx(Router, { children: _jsxs(Routes, { children: [_jsx(Route, { index: true, element: _jsx(Home, {}) }), _jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "galaxy", element: _jsx(Galaxy, {}) }), _jsx(Route, { path: "phonebook", element: _jsx(Tracks.Tracks, {}) }), _jsx(Route, { path: "auth/*", element: _jsx(Tracks.Tracks, {}) }), _jsx(Route, { path: "italy", element: _jsx(ItalyGrid, { images: italyImages, captions: italyCaps }) }), _jsx(Route, { path: "advent", element: _jsx(Advent, {}) }), _jsx(Route, { path: "advent/1", element: _jsx(One, {}) }), _jsx(Route, { path: "advent/2", element: _jsx(Two, {}) }), _jsx(Route, { path: "advent/3", element: _jsx(Three, {}) }), _jsx(Route, { path: "advent/8", element: _jsx(Eight, {}) }), _jsx(Route, { path: "advent/9", element: _jsx(Nine, {}) }), _jsx(Route, { path: "advent/10", element: _jsx(Ten, {}) }), _jsx(Route, { path: "advent/11", element: _jsx(Eleven, {}) }), _jsx(Route, { path: "advent/12", element: _jsx(Twelve, {}) }), _jsx(Route, { path: "advent/13", element: _jsx(Thirteen, {}) }), _jsx(Route, { path: "advent/14", element: _jsx(Fourteen, {}) }), _jsx(Route, { path: "advent/15", element: _jsx(Fifteen, {}) }), _jsx(Route, { path: "advent/16", element: _jsx(Sixteen, {}) }), _jsx(Route, { path: "advent/17", element: _jsx(Seventeen, {}) })] }) }) }));
};
export default App;
